### ISSUE TITLE
Staging fails when deploying to Bluemix

### ISSUE THREAD

**Issue by Dadle88** [watson-developer-cloud/discovery-starter-kit#66]
Hi, just tried to deploy the Discovery-starter-kit to Bluemix and run deploymnet from the toolchain through Orion IDE, but keep receiving an error during staging when installing requirements.

Any input on how to resolve the error where pip install is not able to find the README.md file in your setup?

This is the error log from cf logs appname when no changes have been made to files:
2017-09-10T16:37:50.34+0200 [STG/0] OUT -------> Buildpack version 1.5.15
   2017-09-10T16:37:50.51+0200 [STG/0] OUT  !     Warning: Your application is missing a Procfile. This file tells Cloud Foundry how to run your application.
   2017-09-10T16:37:50.51+0200 [STG/0] OUT  !     Learn more: https://docs.cloudfoundry.org/buildpacks/prod-server.html#procfile
   2017-09-10T16:37:57.55+0200 [STG/0] OUT      $ pip install -r requirements.txt
   2017-09-10T16:37:58.78+0200 [STG/0] OUT        Obtaining file:///tmp/app (from -r requirements.txt (line 1))
   2017-09-10T16:37:59.21+0200 [STG/0] ERR Command "python setup.py egg_info" failed with error code 1 in /tmp/app/
   2017-09-10T16:37:59.24+0200 [STG/0] OUT            Complete output from command python setup.py egg_info:
   2017-09-10T16:37:59.24+0200 [STG/0] OUT              File "<string>", line 1, in <module>
   2017-09-10T16:37:59.24+0200 [STG/0] OUT                file = __builtin__.open(filename, mode, buffering)
   2017-09-10T16:37:59.24+0200 [STG/0] OUT            ----------------------------------------
   2017-09-10T16:37:59.24+0200 [STG/0] OUT            Traceback (most recent call last):
   2017-09-10T16:37:59.24+0200 [STG/0] OUT              File "/tmp/app/setup.py", line 10, in <module>
   2017-09-10T16:37:59.24+0200 [STG/0] OUT                with open(path.join(here, 'README.md'), encoding='utf-8') as f:
   2017-09-10T16:37:59.24+0200 [STG/0] OUT              File "/app/.heroku/python/lib/python2.7/codecs.py", line 896, in open
   2017-09-10T16:37:59.24+0200 [STG/0] OUT            IOError: [Errno 2] No such file or directory: '/tmp/app/README.md'
   2017-09-10T16:37:59.24+0200 [STG/0] OUT
   2017-09-10T16:37:59.47+0200 [STG/0] ERR Failed to compile droplet
   2017-09-10T16:37:59.47+0200 [STG/0] OUT Exit status 223
   2017-09-10T16:37:59.58+0200 [STG/0] ERR Staging failed: Exited with status 223
   2017-09-10T16:37:59.60+0200 [STG/0] OUT Destroying container
   2017-09-10T16:38:03.08+0200 [STG/0] OUT Successfully destroyed container

**Comment by jeanlange** [comment]
Hi, @Dadle88 - thanks for trying out deploying to BM.

I just ran through the steps and successfully deployed - including the step that is causing problems for you. We have never seen this particular error. A difference is that I wasn't using Orion IDE, just the command line. We deliberately didn't include Orion in this toolchain to reduce the complexity of it.

I recommend that you try one or more of the following steps in order to move forward:
- exactly what you were doing, except using the command line instead of Orion.
- running the deploy step of the delivery pipeline after manually creating properly-named empty collections
- potentially loading documents and doing training manually, via the discovery tooling, instead of or in addition to working with the Python scripts.

Let us know how it goes for you!

**Comment by jeanlange** [comment]
Closing issue, please let us know if you see a problem again.
